### ISSUE TITLE
Display chess board

### ISSUE THREAD

**Issue by niesmaczne** [WSB-2023-Informatyka/ML-Chess#1]
### Description

Basic chess board should be displayed in the GUI. 
Library:  Pygame 

Example function:
```
def draw_chessboard(surface):
    for i in range(0, 8):
        for j in range(0, 8):
            if (i + j) % 2 == 0:
                pygame.draw.rect(surface, black, (i * 87, j * 87, 87, 87))
```

It's important to use buffer for keeping chessboard in memory otherwise it will be generated every iteration and it will cause blinking.

```
back_buffer = pygame.Surface((screen.get_width(), screen.get_height()))
back_buffer.fill(white)

__________________

draw_chessboard(back_buffer)

_________


screen.blit(back_buffer, (0, 0))

```

### Area
User Interface

**Comment by Magulak** [comment]
Code changes made in Pycharm, if this will cause issues I will use VS
