### ISSUE TITLE
Choose Chess piece design that will be used in our project.

### ISSUE THREAD

**Issue by Magulak** [WSB-2023-Informatyka/ML-Chess#12]
### Description

Currently we can use any design, but we should decide on one that will fit rest of our project. I suggest going for minimalistic design.

### Area

User Interface

**Comment by niesmaczne** [comment]
1) https://github.com/sense-chess/artwork/tree/master/pieces
2) https://github.com/neverRare/kiwen-suwi/tree/master/version/2.100/kiwen-suwi
3) https://github.com/mganjoo/gchessboard/tree/main/pieces

**Comment by Magulak** [comment]
Nr 2 has very nice look to it but nr 3 has probably the best readability. I would opt for nr 3.

**Comment by Magulak** [comment]
After conducting a meeting in a matter of github issues, it appears that option number 2 is highly readable, and a majority of the team members have chosen this option.

**Comment by Magulak** [comment]
Sense is final choice
