### ISSUE TITLE
What chess engine library will fit our project?

### ISSUE THREAD

**Issue by Magulak** [WSB-2023-Informatyka/ML-Chess#13]
### Description

Due to limitted amount of time and resources we decided on using chess library for our engine. What chess library will fit our project? Data used for model training is already filtered by chess engine(no illegal moves in dataset) so we do not need to worry about it's compatibility with tensorflow.

### Area

Other

**Comment by niesmaczne** [comment]
We can consider: https://github.com/niklasf/python-chess

**Comment by niesmaczne** [comment]
Advantages:
- Compatible with PGN notation
- 2.1k stars and 467 forks
- GPL-3.0 licence
- Move generation and validation
- Support different chess variants
- Endgame tablebase probing: gaviota, syzygy
- UCI/Xboard engine communication
- .svg rendering support

**Comment by Magulak** [comment]
Your suggested option appears to be a highly promising! Great choice!
