### ISSUE TITLE
Research chess notations

### ISSUE THREAD

**Issue by Magulak** [WSB-2023-Informatyka/ML-Chess#5]
### Description

Issue releted to issure nr.: #2

We need to decide what chess notation we will use.

The more difficult to visualise it will be, the harder it will be to implement changes/features into it.

Example notations:

https://www.chess.com/terms/fen-chess
https://en.wikipedia.org/wiki/Algebraic_notation_(chess)

My suggestion:
PGN notation

### Area

User Interface

**Comment by Magulak** [comment]
Issue may be also related to issue #6 . We may use notation that is used in database, it may resolve conversion issues before they appear. Research needed.

**Comment by niesmaczne** [comment]
After research, I agree that **PGN notation** would be the best option. It is very simple while maintaining many details that will make our work easier. In addition, for PGN we can find many examples of games that will make it easier for us to train.

**Comment by Magulak** [comment]
Great !
